import os


STOREOPS_MQTT_SSL_SERVER = os.getenv("STOREOPS_MQTT_SSL_SERVER", default="storeops_mqttbroker.checkpoint-service.com")
STOREOPS_MQTT_SSL_PORT = int(os.getenv("STOREOPS_MQTT_SSL_PORT", default=8883))
STOREOPS_SERVER_SSL_USERNAME = os.getenv("STOREOPS_SERVER_SSL_USERNAME", default="sfero-cert")
STOREOPS_SERVER_SSL_PASSWORD = os.getenv("STOREOPS_SERVER_SSL_PASSWORD", default="")

STOREOPS_MQTT_SSL_CA_CERTIFICATE_PATH =os.getenv("STOREOPS_MQTT_SSL_CA_CERTIFICATE_PATH" )
STOREOPS_MQTT_SSL_KEY_CERTIFICATE_PATH = os.getenv("STOREOPS_MQTT_SSL_KEY_CERTIFICATE_PATH")
STOREOPS_FOLDER_SSL = os.getenv("STOREOPS_FOLDER_SSL", default="./certificates/broker")


STOREOPS_RETRY_SEND_MIN = os.getenv("STOREOPS_RETRY_SEND_MIN", default=5)
STOREOPS_KEEP_MESSAGES_DAYS = os.getenv("STOREOPS_KEEP_MESSAGES_DAYS", default=7)
STOREOPS_CHECK_OLD_MESSAGES_HOURS = os.getenv("STOREOPS_CHECK_OLD_MESSAGES_HOURS", default=8)
STOREOPS_CERTIFICATES_REQUEST_RETRY_SECS = os.getenv("STOREOPS_CERTIFICATES_REQUEST_RETRY_SECS", default=5.0)
 



STOREOPS_CERTIFICATES_REQUEST_USER = os.getenv("STOREOPS_CERTIFICATES_REQUEST_USER", default="mqttuser")
STOREOPS_CERTIFICATES_REQUEST_PASS = os.getenv("STOREOPS_CERTIFICATES_REQUEST_PASS", default="K6W1qyR$2Qmz4Iu")
STOREOPS_CERTIFICATES_REQUEST_URL = os.getenv("STOREOPS_CERTIFICATES_REQUEST_URL", default="https://storeops_certserver.checkpoint-service.com")

STOREOPS_CERTIFICATES_DOWNLOAD_URL = os.getenv("STOREOPS_CERTIFICATES_REQUEST_URL", default=f"{STOREOPS_CERTIFICATES_REQUEST_URL}/download")

STOREOPS_CERTIFICATES_REQUEST_URL_PEM = os.getenv("STOREOPS_CERTIFICATES_REQUEST_URL_PEM", default="./certificates/server/client.pem")
STOREOPS_CERTIFICATES_REQUEST_URL_KEY = os.getenv("STOREOPS_CERTIFICATES_REQUEST_URL_PEM", default="./certificates/server/private.key")

STOREOPS_CERTIFICATES_REQUEST_PORT = os.getenv("STOREOPS_CERTIFICATES_REQUEST_PORT", default=443)
STOREOPS_CERTIFICATES_REQUEST_DESCRIPTION = os.getenv("STOREOPS_CERTIFICATES_REQUEST_DESCRIPTION", default="Certificate default")


